<?php
// database/seeders/KegiatanSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KegiatanSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.03', 'nomenklatur' => 'Pengelolaan Pendidikan Anak Usia Dini (PAUD)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.01.02.04', 'nomenklatur' => 'Pengelolaan Pendidikan Nonformal/Kesetaraan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.02.02.01', 'nomenklatur' => 'Pengelolaan Pendidikan Sekolah Dasar'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.02.02.02', 'nomenklatur' => 'Pengelolaan Pendidikan Sekolah Menengah Pertama'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.02.02.03', 'nomenklatur' => 'Pengelolaan Pendidikan Anak Usia Dini (PAUD)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.02.02.04', 'nomenklatur' => 'Pengelolaan Pendidikan Nonformal/Kesetaraan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.01.04.02.01', 'nomenklatur' => 'Pemerataan Kuantitas dan Kualitas Pendidik dan Tenaga Kependidikan bagi Satuan Pendidikan Dasar, PAUD, dan Pendidikan Nonformal/Kesetaraan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.01.02.10', 'nomenklatur' => 'Peningkatan Pelayanan BLUD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.02.02.01', 'nomenklatur' => 'Penyediaan Fasilitas Pelayanan Kesehatan untuk UKM dan UKP Kewenangan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.02.02.02', 'nomenklatur' => 'Penyediaan Layanan Kesehatan untuk UKM dan UKP Rujukan Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.02.02.03', 'nomenklatur' => 'Penyelenggaraan Sistem Informasi Kesehatan Secara Terintegrasi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.02.02.04', 'nomenklatur' => 'Penerbitan Izin Rumah Sakit Kelas C, D dan Fasilitas Pelayanan Kesehatan Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.02.02.10', 'nomenklatur' => 'Peningkatan Pelayanan BLUD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.03.02.01', 'nomenklatur' => 'Pemberian Izin Praktik Tenaga Kesehatan di Wilayah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.03.02.02', 'nomenklatur' => 'Perencanaan Kebutuhan dan Pendayagunaan Sumber Daya Manusia Kesehatan untuk UKP dan UKM di Wilayah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.03.02.03', 'nomenklatur' => 'Pengembangan Mutu dan Peningkatan Kompetensi Teknis Sumber Daya Manusia Kesehatan Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.04.02.01', 'nomenklatur' => 'Pemberian Izin Apotek, Toko Obat, Toko Alat Kesehatan dan Optikal, Usaha Mikro Obat Tradisional (UMOT)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.04.02.03', 'nomenklatur' => 'Penerbitan Sertifikat Produksi Pangan Industri Rumah Tangga dan Nomor P-IRT sebagai Izin Produksi, untuk Produk Makanan Minuman Tertentu yang Dapat Diproduksi oleh Industri Rumah Tangga'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.04.02.04', 'nomenklatur' => 'Penerbitan Sertifikat Laik Higiene Sanitasi Tempat Pengelolaan Makanan (TPM) antara lain Jasa Boga, Rumah Makan/Restoran dan Depot Air Minum (DAM)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.04.02.05', 'nomenklatur' => 'Penerbitan Stiker Pembinaan pada Makanan Jajanan dan Sentra Makanan Jajanan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.04.02.06', 'nomenklatur' => 'Pemeriksaan dan Tindak Lanjut Hasil Pemeriksaan Post Market pada Produksi dan Produk Makanan Minuman Industri Rumah Tangga'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.05.02.01', 'nomenklatur' => 'Advokasi, Pemberdayaan, Kemitraan, Peningkatan Peran serta Masyarakat dan Lintas Sektor Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.05.02.02', 'nomenklatur' => 'Pelaksanaan Sehat dalam rangka Promotif Preventif Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.02.05.02.03', 'nomenklatur' => 'Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM) Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.02.02.01', 'nomenklatur' => 'Pengelolaan SDA dan Bangunan Pengaman Pantai pada Wilayah Sungai (WS) dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.02.02.02', 'nomenklatur' => 'Pengembangan dan Pengelolaan Sistem Irigasi Primer dan Sekunder pada Daerah Irigasi yang Luasnya di Bawah 1000 Ha dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.03.02.01', 'nomenklatur' => 'Pengelolaan dan Pengembangan Sistem Penyediaan Air Minum (SPAM) di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.05.02.01', 'nomenklatur' => 'Pengelolaan dan Pengembangan Sistem Air Limbah Domestik dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.06.02.01', 'nomenklatur' => 'Pengelolaan dan Pengembangan Sistem Drainase yang Terhubung Langsung dengan Sungai dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.07.02.01', 'nomenklatur' => 'Penyelenggaraan Infrastruktur pada Permukiman di Kawasan Strategis Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.08.02.01', 'nomenklatur' => 'Penyelenggaraan Bangunan Gedung di Wilayah Daerah Kabupaten/Kota, Pemberian Izin Mendirikan Bangunan (IMB) dan Sertifikat Laik Fungsi Bangunan Gedung'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.09.02.01', 'nomenklatur' => 'Penyelenggaraan Penataan Bangunan dan Lingkungannya di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.10.02.01', 'nomenklatur' => 'Penyelenggaraan Jalan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.11.02.01', 'nomenklatur' => 'Penyelenggaraan Pelatihan Tenaga Terampil Konstruksi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.11.02.02', 'nomenklatur' => 'Penyelenggaraan Sistem Informasi Jasa Konstruksi Cakupan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.12.02.01', 'nomenklatur' => 'Penetapan Rencana Tata Ruang Wilayah (RTRW) dan Rencana Rinci Tata Ruang (RRTR) Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.12.02.02', 'nomenklatur' => 'Koordinasi dan Sinkronisasi Perencanaan Tata Ruang Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.12.02.03', 'nomenklatur' => 'Koordinasi dan Sinkronisasi Pemanfaatan Ruang Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.03.12.02.04', 'nomenklatur' => 'Koordinasi dan Sinkronisasi Pengendalian Pemanfaatan Ruang Daerah Kabupaten/Kota'],

            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.02.02.01', 'nomenklatur' => 'Pendataan Penyediaan dan Rehabilitasi Rumah Korban Bencana atau Relokasi Program Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.02.02.02', 'nomenklatur' => 'Sosialisasi dan Persiapan Penyediaan dan Rehabilitasi Rumah Korban Bencana atau Relokasi Program Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.02.02.03', 'nomenklatur' => 'Pembangunan dan Rehabilitasi Rumah Korban Bencana atau Relokasi Program Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.02.02.04', 'nomenklatur' => 'Pendistribusian dan Serah Terima Rumah bagi Korban Bencana atau Relokasi Program Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.03.02.01', 'nomenklatur' => 'Penerbitan Izin Pembangunan dan Pengembangan Kawasan Permukiman'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.03.02.03', 'nomenklatur' => 'Peningkatan Kualitas Kawasan Permukiman Kumuh dengan Luas di Bawah 10 (Sepuluh) Ha'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.04.05.02.01', 'nomenklatur' => 'Urusan Penyelenggaraan PSU Perumahan'],
        
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.02.02.01', 'nomenklatur' => 'Penanganan Gangguan Ketenteraman dan Ketertiban Umum dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.02.02.02', 'nomenklatur' => 'Penegakan Peraturan Daerah Kabupaten/Kota dan Peraturan Bupati/Wali Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.02.02.03', 'nomenklatur' => 'Pembinaan Penyidik Pegawai Negeri Sipil (PPNS) Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.03.02.01', 'nomenklatur' => 'Pelayanan Informasi Rawan Bencana Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.03.02.02', 'nomenklatur' => 'Pelayanan Pencegahan dan Kesiapsiagaan Terhadap Bencana'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.03.02.03', 'nomenklatur' => 'Pelayanan Penyelamatan dan Evakuasi Korban Bencana'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.01', 'nomenklatur' => 'Pencegahan, Pengendalian, Pemadaman, Penyelamatan, dan Penanganan Bahan Berbahaya dan Beracun Kebakaran dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.02', 'nomenklatur' => 'Inspeksi Peralatan Proteksi Kebakaran'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.04', 'nomenklatur' => 'Pemberdayaan Masyarakat dalam Pencegahan Kebakaran'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.05', 'nomenklatur' => 'Penyelenggaraan Operasi Pencarian dan Pertolongan Terhadap Kondisi Membahayakan Manusia'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.05.04.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.02.02.02', 'nomenklatur' => 'Pengumpulan Sumbangan dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.02.02.03', 'nomenklatur' => 'Pengembangan Potensi Sumber Kesejahteraan Sosial Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.03.02.01', 'nomenklatur' => 'Pemulangan Warga Negara Migran Korban Tindak Kekerasan dari Titik Debarkasi di Daerah Kabupaten/Kota untuk Dipulangkan ke Desa/Kelurahan Asal'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.04.02.01', 'nomenklatur' => 'Rehabilitasi Sosial Dasar Penyandang Disabilitas Terlantar, Anak Terlantar, Lanjut Usia Terlantar, serta Gelandangan Pengemis di Luar Panti Sosial'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.04.02.02', 'nomenklatur' => 'Rehabilitasi Sosial Penyandang Masalah Kesejahteraan Sosial (PMKS) Lainnya Bukan Korban HIV/AIDS dan NAPZA di Luar Panti Sosial'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.05.02.01', 'nomenklatur' => 'Pemeliharaan Anak-Anak Terlantar'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.05.02.02', 'nomenklatur' => 'Pengelolaan Data Fakir Miskin Cakupan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.06.02.01', 'nomenklatur' => 'Perlindungan Sosial Korban Bencana Alam dan Sosial Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.06.02.02', 'nomenklatur' => 'Penyelenggaraan Pemberdayaan Masyarakat Terhadap Kesiapsiagaan Bencana Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '1.06.07.02.01', 'nomenklatur' => 'Pemeliharaan Taman Makam Pahlawan Nasional Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.03.02.01', 'nomenklatur' => 'Pelaksanaan Pelatihan berdasarkan Unit Kompetensi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.03.02.02', 'nomenklatur' => 'Pembinaan Lembaga Pelatihan Kerja Swasta'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.03.02.05', 'nomenklatur' => 'Pengukuran Produktivitas Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.04.02.01', 'nomenklatur' => 'Pelayanan antar Kerja di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.04.02.03', 'nomenklatur' => 'Pengelolaan Informasi Pasar Kerja'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.04.02.04', 'nomenklatur' => 'Pelindungan PMI (Pra dan Purna Penempatan) di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.05.02.01', 'nomenklatur' => 'Pengesahan Peraturan Perusahaan dan Pendaftaran Perjanjian Kerja Bersama untuk Perusahaan yang Hanya Beroperasi dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.07.05.02.02', 'nomenklatur' => 'Pencegahan dan Penyelesaian Perselisihan Hubungan Industrial, Mogok Kerja dan Penutupan Perusahaan di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.02.02.01', 'nomenklatur' => 'Pelembagaan Pengarusutamaan Gender (PUG) pada Lembaga Pemerintah Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.02.02.02', 'nomenklatur' => 'Pemberdayaan Perempuan Bidang Politik, Hukum, Sosial, dan Ekonomi pada Organisasi Kemasyarakatan Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.02.02.03', 'nomenklatur' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Pemberdayaan Perempuan Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.03.02.01', 'nomenklatur' => 'Pencegahan Kekerasan Terhadap Perempuan Lingkup Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.03.02.02', 'nomenklatur' => 'Penyediaan Layanan Rujukan Lanjutan bagi Perempuan Korban Kekerasan yang Memerlukan Koordinasi Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.03.02.03', 'nomenklatur' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Perlindungan Perempuan Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.04.02.01', 'nomenklatur' => 'Peningkatan Kualitas Keluarga dalam Mewujudkan Kesetaraan Gender (KG) dan Hak Anak Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.04.02.02', 'nomenklatur' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Peningkatan Kualitas Keluarga dalam Mewujudkan KG dan Hak Anak yang Wilayah Kerjanya dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.04.02.03', 'nomenklatur' => 'Penyediaan Layanan bagi Keluarga dalam Mewujudkan KG dan Hak Anak yang Wilayah Kerjanya dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.05.02.01', 'nomenklatur' => 'Pengumpulan, Pengolahan Analisis dan Penyajian Data Gender dan Anak Dalam Kelembagaan Data di Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.06.02.01', 'nomenklatur' => 'Pelembagaan PHA pada Lembaga Pemerintah, Nonpemerintah, dan Dunia Usaha Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.06.02.02', 'nomenklatur' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Peningkatan Kualitas Hidup Anak Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.07.02.01', 'nomenklatur' => 'Pencegahan Kekerasan Terhadap Anak yang Melibatkan para Pihak Lingkup Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.07.02.02', 'nomenklatur' => 'Penyediaan Layanan bagi Anak yang Memerlukan Perlindungan Khusus yang Memerlukan Koordinasi Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.08.07.02.03', 'nomenklatur' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan bagi Anak yang Memerlukan Perlindungan Khusus Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.02.02.01', 'nomenklatur' => 'Penyediaan Infrastruktur dan Seluruh Pendukung Kemandirian Pangan sesuai Kewenangan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.03.02.01', 'nomenklatur' => 'Penyediaan dan Penyaluran Pangan Pokok atau Pangan Lainnya sesuai dengan Kebutuhan Daerah Kabupaten/Kota dalam rangka Stabilisasi Pasokan dan Harga Pangan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.03.02.02', 'nomenklatur' => 'Pengelolaan dan Keseimbangan Cadangan Pangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.03.02.04', 'nomenklatur' => 'Pelaksanaan Pencapaian Target Konsumsi Pangan Perkapita/Tahun sesuai dengan Angka Kecukupan Gizi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.04.02.01', 'nomenklatur' => 'Penyusunan Peta Kerentanan dan Ketahanan Pangan Kecamatan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.04.02.02', 'nomenklatur' => 'Penanganan Kerawanan Pangan Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.09.05.02.01', 'nomenklatur' => 'Pelaksanaan Pengawasan Keamanan Pangan Segar Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.10.04.02.01', 'nomenklatur' => 'Penyelesaian Sengketa Tanah Garapan dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.10.05.02.01', 'nomenklatur' => 'Penyelesaian Masalah Ganti Kerugian dan Santunan Tanah untuk Pembangunan oleh Pemerintah Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.10.08.02.02', 'nomenklatur' => 'Inventarisasi dan Pemanfaatan Tanah Kosong'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.02.02.02', 'nomenklatur' => 'Penyelenggaraan Kajian Lingkungan Hidup Strategis (KLHS) Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.03.02.01', 'nomenklatur' => 'Pencegahan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.04.02.01', 'nomenklatur' => 'Pengelolaan Keanekaragaman Hayati Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.05.02.01', 'nomenklatur' => 'Penyimpanan sementara Limbah B3'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.06.02.01', 'nomenklatur' => 'Pembinaan dan Pengawasan Terhadap Usaha dan/atau Kegiatan yang Izin Lingkungan dan Izin PPLH Diterbitkan oleh Pemerintah Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.09.02.01', 'nomenklatur' => 'Pemberian Penghargaan Lingkungan Hidup Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.10.02.01', 'nomenklatur' => 'Penyelesaian Pengaduan Masyarakat di Bidang Perlindungan dan Pengelolaan Lingkungan Hidup (PPLH) Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.11.11.02.01', 'nomenklatur' => 'Pengelolaan Sampah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.02.02.01', 'nomenklatur' => 'Pelayanan Pendaftaran Penduduk'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.02.02.03', 'nomenklatur' => 'Penyelenggaraan Pendaftaran Penduduk'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.03.02.01', 'nomenklatur' => 'Pelayanan Pencatatan Sipil'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.03.02.02', 'nomenklatur' => 'Penyelenggaraan Pencatatan Sipil'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.04.02.01', 'nomenklatur' => 'Pengumpulan Data Kependudukan dan Pemanfaatan dan Penyajian Database Kependudukan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.04.02.03', 'nomenklatur' => 'Penyelenggaraan Pengelolaan Informasi Administrasi Kependudukan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.12.05.02.01', 'nomenklatur' => 'Penyusunan Profil Kependudukan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.02.02.01', 'nomenklatur' => 'Pemaduan dan Sinkronisasi Kebijakan Pemerintah Daerah Provinsi dengan Pemerintah Daerah Kabupaten/Kota dalam rangka Pengendalian Kuantitas Penduduk'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.02.02.02', 'nomenklatur' => 'Pemetaan Perkiraan Pengendalian Penduduk Cakupan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.03.02.01', 'nomenklatur' => 'Pelaksanaan Advokasi, Komunikasi, Informasi dan Edukasi (KIE) Pengendalian Penduduk dan KB Sesuai Kearifan Budaya Lokal'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.03.02.02', 'nomenklatur' => 'Pendayagunaan Tenaga Penyuluh KB/Petugas Lapangan KB (PKB/PLKB)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.03.02.03', 'nomenklatur' => 'Pengendalian dan Pendistribusian Kebutuhan Alat dan Obat Kontrasepsi serta Pelaksanaan Pelayanan KB di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.03.02.04', 'nomenklatur' => 'Pemberdayaan dan Peningkatan Peran Serta Organisasi Kemasyarakatan Tingkat Daerah Kabupaten/Kota dalam Pelaksanaan Pelayanan dan Pembinaan Kesertaan Ber-KB'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.04.02.01', 'nomenklatur' => 'Pelaksanaan Pembangunan Keluarga Melalui Pembinaan Ketahanan dan Kesejahteraan Keluarga'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.14.04.02.02', 'nomenklatur' => 'Pelaksanaan dan Peningkatan Peran Serta Organisasi Kemasyarakatan Tingkat Daerah Kabupaten/ Kota dalam Pembangunan Keluarga Melalui Pembinaan Ketahanan dan Kesejahteraan Keluarga'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.01', 'nomenklatur' => 'Penetapan Rencana Induk Jaringan LLAJ Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.02', 'nomenklatur' => 'Penyediaan Perlengkapan Jalan di Jalan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.03', 'nomenklatur' => 'Pengelolaan Terminal Penumpang Tipe C'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.04', 'nomenklatur' => 'Penerbitan Izin Penyelenggaraan dan Pembangunan Fasilitas Parkir'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.05', 'nomenklatur' => 'Pengujian Berkala Kendaraan Bermotor'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.06', 'nomenklatur' => 'Pelaksanaan Manajemen dan Rekayasa Lalu Lintas untuk Jaringan Jalan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.07', 'nomenklatur' => 'Persetujuan Hasil Analisis Dampak Lalu Lintas (Andalalin) untuk Jalan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.09', 'nomenklatur' => 'Penyediaan Angkutan Umum untuk Jasa Angkutan Orang dan/atau Barang Antar Kota dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.11', 'nomenklatur' => 'Penetapan Rencana Umum Jaringan Trayek Perkotaan dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.15.02.02.16', 'nomenklatur' => 'Penetapan Tarif Kelas Ekonomi untuk Angkutan Orang yang Melayani Trayek serta Angkutan Perkotaan dan Perdesaan dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.04', 'nomenklatur' => 'Administrasi Pendapatan Daerah Kewenangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.02.02.01', 'nomenklatur' => 'Pengelolaan Informasi dan Komunikasi Publik Pemerintah Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.03.02.01', 'nomenklatur' => 'Pengelolaan Nama Domain yang Telah Ditetapkan oleh Pemerintah Pusat dan Sub Domain di Lingkup Pemerintah Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.16.03.02.02', 'nomenklatur' => 'Pengelolaan E-government di Lingkup Pemerintah Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.17.03.02.01', 'nomenklatur' => 'Pemeriksaan dan Pengawasan Koperasi, Koperasi Simpan Pinjam/Unit Simpan Pinjam Koperasi yang Wilayah Keanggotaannya dalam Daerah Kabupaten/ Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.17.04.02.01', 'nomenklatur' => 'Penilaian Kesehatan Koperasi Simpan Pinjam/Unit Simpan Pinjam Koperasi yang Wilayah Keanggotaanya dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.17.05.02.01', 'nomenklatur' => 'Pendidikan dan Latihan Perkoperasian Bagi Koperasi yang Wilayah Keanggotaan dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.17.06.02.01', 'nomenklatur' => 'Pemberdayaan dan Perlindungan Koperasi yang Keanggotaannya dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.17.07.02.01', 'nomenklatur' => 'Pemberdayaan Usaha Mikro yang Dilakukan Melalui Pendataan, Kemitraan, Kemudahan Perizinan, Penguatan Kelembagaan dan Koordinasi dengan Para Pemangku Kepentingan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.02.02.01', 'nomenklatur' => 'Penetapan Pemberian Fasilitas/Insentif Dibidang Penanaman Modal yang Menjadi Kewenangan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.02.02.02', 'nomenklatur' => 'Pembuatan Peta Potensi Investasi Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.03.02.01', 'nomenklatur' => 'Penyelenggaraan Promosi Penanaman Modal yang Menjadi Kewenangan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.04.02.01', 'nomenklatur' => 'Pelayanan Perizinan dan Non Perizinan Secara Terpadu Satu Pintu dibidang Penanaman Modal yang Menjadi Kewenangan Daerah Kabupaten/ Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.05.02.01', 'nomenklatur' => 'Pengendalian Pelaksanaan Penanaman Modal yang Menjadi Kewenangan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.18.06.02.01', 'nomenklatur' => 'Pengelolaan Data dan Informasi Perizinan dan Non Perizinan yang Terintegrasi pada Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.04', 'nomenklatur' => 'Administrasi Pendapatan Daerah Kewenangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.02.02.01', 'nomenklatur' => 'Penyadaran, Pemberdayaan, dan Pengembangan Pemuda dan Kepemudaan Terhadap Pemuda Pelopor Kabupaten/Kota, Wirausaha Muda Pemula, dan Pemuda Kader Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.02.02.02', 'nomenklatur' => 'Pemberdayaan dan Pengembangan Organisasi Kepemudaan Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.03.02.01', 'nomenklatur' => 'Pembinaan dan Pengembangan Olahraga Pendidikan pada Jenjang Pendidikan yang Menjadi Kewenangan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.03.02.02', 'nomenklatur' => 'Penyelenggaraan Kejuaraan Olahraga Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.03.02.03', 'nomenklatur' => 'Pembinaan dan Pengembangan Olahraga Prestasi Tingkat Daerah Provinsi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.03.02.04', 'nomenklatur' => 'Pembinaan dan Pengembangan Organisasi Olahraga'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.03.02.05', 'nomenklatur' => 'Pembinaan dan Pengembangan Olahraga Rekreasi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.19.04.02.01', 'nomenklatur' => 'Pembinaan dan Pengembangan Organisasi Kepramukaan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.20.02.02.01', 'nomenklatur' => 'Penyelenggaraan Statistik Sektoral di Lingkup Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.21.02.02.01', 'nomenklatur' => 'Penyelenggaraan Persandian untuk Pengamanan Informasi Pemerintah Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.21.02.02.02', 'nomenklatur' => 'Penetapan Pola Hubungan Komunikasi Sandi Antar Perangkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.02.02.01', 'nomenklatur' => 'Pengelolaan Kebudayaan yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.02.02.02', 'nomenklatur' => 'Pelestarian Kesenian Tradisional yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.03.02.01', 'nomenklatur' => 'Pembinaan Kesenian yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.04.02.01', 'nomenklatur' => 'Pembinaan Sejarah Lokal dalam 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.05.02.01', 'nomenklatur' => 'Penetapan Cagar Budaya Peringkat Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.05.02.02', 'nomenklatur' => 'Pengelolaan Cagar Budaya Peringkat Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.22.06.02.01', 'nomenklatur' => 'Pengelolaan Museum Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.02.02.01', 'nomenklatur' => 'Pengelolaan Perpustakaan Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.02.02.02', 'nomenklatur' => 'Pembudayaan Gemar Membaca Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.23.03.02.01', 'nomenklatur' => 'Pelestarian Naskah Kuno Milik Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.24.02.02.01', 'nomenklatur' => 'Pengelolaan Arsip Dinamis Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.24.02.02.02', 'nomenklatur' => 'Pengelolaan Arsip Statis Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.24.02.02.03', 'nomenklatur' => 'Pengelolaan Simpul Jaringan Informasi Kearsipan Nasional Tingkat Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.24.03.02.01', 'nomenklatur' => 'Pemusnahan Arsip Dilingkungan Pemerintah Daerah Kabupaten/Kota yang Memiliki Retensi di Bawah 10 (Sepuluh) Tahun'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.24.03.02.04', 'nomenklatur' => 'Autentikasi Arsip Statis dan Arsip Hasil Alih Media Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '2.24.04.02.01', 'nomenklatur' => 'Pelayanan Izin Penggunaan Arsip yang Bersifat Tertutup di Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.03.02.01', 'nomenklatur' => 'Pengelolaan Penangkapan Ikan di Wilayah Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang Dapat Diusahakan dalam 1 (Satu) Daerah Kabupaten/ Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.03.02.02', 'nomenklatur' => 'Pemberdayaan Nelayan Kecil dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.03.02.03', 'nomenklatur' => 'Pengelolaan dan Penyelenggaraan Tempat Pelelangan Ikan (TPI)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.04.02.02', 'nomenklatur' => 'Pemberdayaan Pembudi Daya Ikan Kecil'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.04.02.04', 'nomenklatur' => 'Pengelolaan Pembudidayaan Ikan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.06.02.01', 'nomenklatur' => 'Penerbitan Tanda Daftar Usaha Pengolahan Hasil Perikanan bagi Usaha Skala Mikro dan Kecil'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.06.02.02', 'nomenklatur' => 'Pembinaan Mutu dan Keamanan Hasil Perikanan bagi Usaha Pengolahan dan Pemasaran Skala Mikro dan Kecil'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.25.06.02.03', 'nomenklatur' => 'Penyediaan dan Penyaluran Bahan Baku Industri Pengolahan Ikan dalam 1 (Satu) Daerah Kabupaten/ Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.02.02.02', 'nomenklatur' => 'Pengelolaan Kawasan Strategis Pariwisata Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.02.02.03', 'nomenklatur' => 'Pengelolaan Destinasi Pariwisata Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.02.02.04', 'nomenklatur' => 'Penetapan Tanda Daftar Usaha Pariwisata Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.03.02.01', 'nomenklatur' => 'Pemasaran Pariwisata Dalam dan Luar Negeri Daya Tarik, Destinasi dan Kawasan Strategis Pariwisata Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.04.02.01', 'nomenklatur' => 'Penyediaan Prasarana (Zona Kreatif/Ruang Kreatif/Kota Kreatif) sebagai Ruang Berekspresi, Berpromosi dan Berinteraksi bagi Insan Kreatif di Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.05.02.01', 'nomenklatur' => 'Pelaksanaan Peningkatan Kapasitas Sumber Daya Manusia Pariwisata dan Ekonomi Kreatif Tingkat Dasar'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.26.05.02.02', 'nomenklatur' => 'Pengembangan Kapasitas Pelaku Ekonomi Kreatif'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.02.02.01', 'nomenklatur' => 'Pengawasan Penggunaan Sarana Pertanian'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.02.02.02', 'nomenklatur' => 'Pengelolaan Sumber Daya Genetik (SDG) Hewan, Tumbuhan, dan Mikro Organisme Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.02.02.03', 'nomenklatur' => 'Peningkatan Mutu dan Peredaran Benih/Bibit Ternak dan Tanaman Pakan Ternak serta Pakan dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.02.02.05', 'nomenklatur' => 'Pengendalian dan Pengawasan Penyediaan dan Peredaran Benih/Bibit Ternak, dan Hijauan Pakan Ternak dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.02.02.06', 'nomenklatur' => 'Penyediaan Benih/Bibit Ternak dan Hijauan Pakan Ternak yang Sumbernya dalam 1 (Satu) Daerah Kabupaten/Kota Lain'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.03.02.01', 'nomenklatur' => 'Pengembangan Prasarana Pertanian'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.03.02.02', 'nomenklatur' => 'Pembangunan Prasarana Pertanian'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.03.02.03', 'nomenklatur' => 'Pengelolaan Wilayah Sumber Bibit Ternak dan Rumpun/Galur Ternak dalam Daerah Kabupaten/ Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.04.02.01', 'nomenklatur' => 'Penjaminan Kesehatan Hewan, Penutupan dan Pembukaan Daerah Wabah Penyakit Hewan Menular Dalam daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.04.02.02', 'nomenklatur' => 'Pengawasan Pemasukan dan Pengeluaran Hewan dan Produk Hewan Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.04.02.03', 'nomenklatur' => 'Pengelolaan Pelayanan Jasa Laboratorium dan Jasa Medik Veteriner dalam Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.04.02.04', 'nomenklatur' => 'Penerapan dan Pengawasan Persyaratan Teknis Kesehatan Masyarakat Veteriner'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.05.02.01', 'nomenklatur' => 'Pengendalian dan Penanggulangan Bencana Pertanian Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.27.07.02.01', 'nomenklatur' => 'Pelaksanaan Penyuluhan Pertanian'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.04', 'nomenklatur' => 'Administrasi Pendapatan Daerah Kewenangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.02.02.01', 'nomenklatur' => 'Penerbitan Izin Pengelolaan Pasar Rakyat, Pusat Perbelanjaan, dan Izin Usaha Toko Swalayan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.03.02.01', 'nomenklatur' => 'Pembangunan dan Pengelolaan Sarana Distribusi Perdagangan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.03.02.02', 'nomenklatur' => 'Pembinaan Terhadap Pengelola Sarana Distribusi Perdagangan Masyarakat di Wilayah Kerjanya'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.04.02.01', 'nomenklatur' => 'Menjamin Ketersediaan Barang Kebutuhan Pokok dan Barang Penting di Tingkat Daerah Kabupaten/ Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.04.02.02', 'nomenklatur' => 'Pengendalian Harga, dan Stok Barang Kebutuhan Pokok dan Barang Penting di Tingkat Pasar Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.04.02.03', 'nomenklatur' => 'Pengawasan Pupuk dan Pestisida Bersubsidi di Tingkat Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.05.02.01', 'nomenklatur' => 'Penyelenggaraan Promosi Dagang Melalui Pameran Dagang dan Misi Dagang bagi Produk Ekspor Unggulan yang Terdapat pada 1 (Satu) Daerah Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.30.06.02.01', 'nomenklatur' => 'Pelaksanaan Metrologi Legal, Berupa Tera, Tera Ulang, dan Pengawasan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.31.02.02.01', 'nomenklatur' => 'Penyusunan dan Evaluasi Rencana Pembangunan Industri Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.31.03.02.01', 'nomenklatur' => 'Penerbitan Izin Usaha Industri (IUI), Izin Perluasan Usaha Industri (IPUI), Izin Usaha Kawasan Industri (IUKI) dan Izin Perluasan Kawasan Industri (IPKI) Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '3.31.04.02.01', 'nomenklatur' => 'Penyediaan Informasi Industri untuk Informasi Industri untuk IUI, IPUI, IUKI dan IPKI Kewenangan Kabupaten/Kota'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.11', 'nomenklatur' => 'Administrasi Keuangan dan Operasional Kepala Daerah dan Wakil Kepala Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.12', 'nomenklatur' => 'Fasilitasi Kerumahtanggaan Sekretariat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.13', 'nomenklatur' => 'Penataan Organisasi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.01.02.14', 'nomenklatur' => 'Pelaksanaan Protokol dan Komunikasi Pimpinan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.02.02.01', 'nomenklatur' => 'Administrasi Tata Pemerintahan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.02.02.02', 'nomenklatur' => 'Pelaksanaan Kebijakan Kesejahteraan Rakyat'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.02.02.03', 'nomenklatur' => 'Fasilitasi dan Koordinasi Hukum'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.02.02.04', 'nomenklatur' => 'Fasilitasi Kerja Sama Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.03.02.01', 'nomenklatur' => 'Pelaksanaan Kebijakan Perekonomian'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.03.02.02', 'nomenklatur' => 'Pelaksanaan Administrasi Pembangunan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.03.02.03', 'nomenklatur' => 'Pengelolaan Pengadaan Barang dan Jasa'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.01.03.02.04', 'nomenklatur' => 'Pemantauan Kebijakan Sumber Daya Alam'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.15', 'nomenklatur' => 'Layanan Keuangan dan Kesejahteraan DPRD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.01.02.16', 'nomenklatur' => 'Layanan Administrasi DPRD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.01', 'nomenklatur' => 'Pembentukan Peraturan Daerah dan Peraturan DPRD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.02', 'nomenklatur' => 'Pembahasan Kebijakan Anggaran'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.03', 'nomenklatur' => 'Pengawasan Penyelenggaraan Pemerintahan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.04', 'nomenklatur' => 'Peningkatan Kapasitas DPRD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.05', 'nomenklatur' => 'Penyerapan dan Penghimpunan Aspirasi Masyarakat'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.06', 'nomenklatur' => 'Pelaksanaan dan Pengawasan Kode Etik DPRD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '4.02.02.02.08', 'nomenklatur' => 'Fasilitasi Tugas DPRD'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.02.02.01', 'nomenklatur' => 'Penyusunan Perencanaan dan Pendanaan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.02.02.02', 'nomenklatur' => 'Analisis Data dan Informasi Pemerintahan Daerah Bidang Perencanaan Pembangunan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.02.02.03', 'nomenklatur' => 'Pengendalian, Evaluasi dan Pelaporan Bidang Perencanaan Pembangunan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.02.02.04', 'nomenklatur' => 'Implementasi Sistem Informasi Pemerintahan Daerah di Bidang Pembangunan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.03.02.01', 'nomenklatur' => 'Koordinasi Perencanaan Bidang Pemerintahan dan Pembangunan Manusia'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.03.02.02', 'nomenklatur' => 'Koordinasi Perencanaan Bidang Perekonomian dan SDA (Sumber Daya Alam)'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.01.03.02.03', 'nomenklatur' => 'Koordinasi Perencanaan Bidang Infrastruktur dan Kewilayahan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.02.02.01', 'nomenklatur' => 'Koordinasi dan Penyusunan Rencana Anggaran Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.02.02.02', 'nomenklatur' => 'Koordinasi dan Pengelolaan Perbendaharaan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.02.02.03', 'nomenklatur' => 'Koordinasi dan Pelaksanaan Akuntansi dan Pelaporan Keuangan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.02.02.04', 'nomenklatur' => 'Penunjang Urusan Kewenangan Pengelolaan Keuangan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.02.02.05', 'nomenklatur' => 'Pengelolaan Data dan Implementasi Sistem Informasi Pemerintah Daerah Lingkup Keuangan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.03.02.01', 'nomenklatur' => 'Pengelolaan Barang Milik Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.02.04.02.01', 'nomenklatur' => 'Kegiatan Pengelolaan Pendapatan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.02.02.01', 'nomenklatur' => 'Pengadaan, Pemberhentian dan Informasi Kepegawaian ASN'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.02.02.02', 'nomenklatur' => 'Mutasi dan Promosi ASN'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.02.02.03', 'nomenklatur' => 'Pengembangan Kompetensi ASN'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.03.02.02.04', 'nomenklatur' => 'Penilaian dan Evaluasi Kinerja Aparatur'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.04.02.02.01', 'nomenklatur' => 'Pengembangan Kompetensi Teknis'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.04.02.02.02', 'nomenklatur' => 'Sertifikasi, Kelembagaan, Pengembangan Kompetensi Manajerial dan Fungsional'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.05.02.02.01', 'nomenklatur' => 'Penelitian dan Pengembangan Bidang Penyelenggaraan Pemerintahan dan Pengkajian Peraturan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.05.02.02.03', 'nomenklatur' => 'Penelitian dan Pengembangan Bidang Ekonomi dan Pembangunan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '5.05.02.02.04', 'nomenklatur' => 'Pengembangan Inovasi dan Teknologi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.02.02.01', 'nomenklatur' => 'Penyelenggaraan Pengawasan Internal'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.02.02.02', 'nomenklatur' => 'Penyelenggaraan Pengawasan dengan Tujuan Tertentu'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.03.02.01', 'nomenklatur' => 'Perumusan Kebijakan Teknis di Bidang Pengawasan dan Fasilitasi Pengawasan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '6.01.03.02.02', 'nomenklatur' => 'Pendampingan dan Asistensi'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.02.02.01', 'nomenklatur' => 'Koordinasi Penyelenggaraan Kegiatan Pemerintahan di Tingkat Kecamatan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.02.02.04', 'nomenklatur' => 'Pelaksanaan Urusan Pemerintahan yang Dilimpahkan kepada Camat'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.03.02.02', 'nomenklatur' => 'Kegiatan Pemberdayaan Kelurahan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.03.02.03', 'nomenklatur' => 'Pemberdayaan Lembaga Kemasyarakatan Tingkat Kecamatan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.03.02.06', 'nomenklatur' => 'Pemberdayaan dan Kesejahteraan Keluarga Tingkat Kecamatan dan Kelurahan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.04.02.01', 'nomenklatur' => 'Koordinasi Upaya Penyelenggaraan Ketenteraman dan Ketertiban Umum'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '7.01.04.02.02', 'nomenklatur' => 'Koordinasi Penerapan dan Penegakan Peraturan Daerah dan Peraturan Kepala Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.01', 'nomenklatur' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.02', 'nomenklatur' => 'Administrasi Keuangan Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.03', 'nomenklatur' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.05', 'nomenklatur' => 'Administrasi Kepegawaian Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.06', 'nomenklatur' => 'Administrasi Umum Perangkat Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.07', 'nomenklatur' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.08', 'nomenklatur' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.01.02.09', 'nomenklatur' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.02.02.01', 'nomenklatur' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Ideologi Pancasila dan Karakter Kebangsaan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.03.02.01', 'nomenklatur' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Pendidikan Politik, Etika Budaya Politik, Peningkatan Demokrasi, Fasilitasi Kelembagaan Pemerintahan, Perwakilan dan Partai Politik, Pemilihan Umum/Pemilihan Umum Kepala Daerah, serta Pemantauan Situasi Politik'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.04.02.01', 'nomenklatur' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Pemberdayaan dan Pengawasan Organisasi Kemasyarakatan'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.05.02.01', 'nomenklatur' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Ketahanan Ekonomi, Sosial dan Budaya'],
            ['jenis_nomenklatur' => 3, 'nomor_kode' => '8.01.06.02.01', 'nomenklatur' => 'Perumusan Kebijakan Teknis dan Pelaksanaan Pemantapan Kewaspadaan Nasional dan Penanganan Konflik Sosial'],
        ];

        foreach ($data as $item) {
            $id = DB::table('kode_nomenklatur')->insertGetId([
                'jenis_nomenklatur' => $item['jenis_nomenklatur'],
                'nomor_kode' => $item['nomor_kode'],
                'nomenklatur' => $item['nomenklatur'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            // breakdown
            $parts = explode('.', $item['nomor_kode']); // e.g. 1.01.01.02.01
            $kode_urusan = $parts[0];
            $kode_bidang = $parts[0] . '.' . $parts[1];
            $kode_program = $parts[0] . '.' . $parts[1] . '.' . $parts[2];

            $id_urusan = DB::table('kode_nomenklatur')->where('jenis_nomenklatur', 0)->where('nomor_kode', $kode_urusan)->value('id');
            $id_bidang = DB::table('kode_nomenklatur')->where('jenis_nomenklatur', 1)->where('nomor_kode', $kode_bidang)->value('id');
            $id_program = DB::table('kode_nomenklatur')->where('jenis_nomenklatur', 2)->where('nomor_kode', $kode_program)->value('id');

            DB::table('kode_nomenklatur_detail')->insert([
                'id_nomenklatur'    => $id,
                'id_urusan'         => $id_urusan,
                'id_bidang_urusan'  => $id_bidang,
                'id_program'        => $id_program,
                'id_kegiatan'       => null,
                'id_sub_kegiatan'   => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ]);
        }
    }
}
